server:
  port: 8001

#配置mysql
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://115.29.110.8:3306/mango?useUnicode=true&zeroDateTimeBehavior = convertToNull&autoReconnet=true&characterEncoding=utf-8
#    username: root
#    password: 123456root
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://115.29.110.8:3306/mango?useUnicode=true&zeroDateTimeBehavior = convertToNull&autoReconnet=true&characterEncoding=utf-8
      username: root
      password: 123456root
      filters: stat,wall,log4j,config  #配置监控统计拦截的filters,去掉后监控界面SQL无法进行统计，wall用于防火墙
      max-active: 100   #最大连接数
      initial-size: 10 #初始化大小
      max-wait: 60000  #获取连接等待的超时时间
      min-idle: 1   #最小连接数
      time-between-eviction-runs-millis: 600000  #间隔多久才进行一次检测，检测需要关闭的空连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 #一个连接在连接池中最小生存时间，单位毫秒
      validation-query: select 'x'
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20

#配置druid